# Copyright 2009 Google Inc. All Rights Reserved.
# Author: scovitz@google.com (Seth Covitz)
#
# Description:
#   Classes related to the Google Wave API.

java_library(name = "api",
             srcs = glob(["*.java",
                          "*/*.java"]),
             deps = ["//third_party/java/jsonrpc:jsonrpc-fulljson",
                     "//third_party/java/jdom"])
